    # .github/workflows/main.yml
    name: Java CI/CD with Docker

    on:
      push:
        branches:
          - main

    jobs:
      build-and-deploy:
        runs-on: ubuntu-latest
        steps:
          - name: Git Checkout
            uses: actions/checkout@v4

          - name: Set up JDK 11
            uses: actions/setup-java@v4
            with:
              java-version: '11'
              distribution: 'temurin'

          - name: Build with Maven
            run: mvn clean package -DskipTests=false

          - name: Test with Maven
            run: mvn test

          - name: Upload Artifact to Cache
            uses: actions/cache@v4
            with:
              path: target/
              key: ${{ runner.os }}-maven-${{ hashFiles('pom.xml') }}
              restore-keys: |
                ${{ runner.os }}-maven-

          - name: Log in to Docker Hub
            uses: docker/login-action@v3
            with:
              username: ${{ secrets.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKER_PASSWORD }}

          - name: Build and push Docker image
            uses: docker/build-push-action@v5
            with:
              context: .
              push: true
              tags: ${{ secrets.DOCKER_USERNAME }}/hello-world:latest

          - name: Run Docker Container (for verification/testing in CI)
            run: |
              docker pull ${{ secrets.DOCKER_USERNAME }}/hello-world:latest
              docker run --name hello-world-app -d -p 8080:8080 ${{ secrets.DOCKER_USERNAME }}/hello-world:latest
              sleep 5 # Give container time to start
              docker logs hello-world-app
